apiVersion: v1
kind: Pod
metadata:
  name: vck-taxi
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: vck.intelai.org/default-vck-taxi-vol-train
            operator: Exists
  volumes:
    - name: dataset-claim
      hostPath:
        path: VCK_HOSTPATH
  containers:
  - image: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 1d"]
    name: vck-sleep
    volumeMounts:
    - mountPath: /data
      name: dataset-claim