apiVersion: v1
kind: Pod
metadata:
  name: vck-taxi
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: vck.intelai.org/default-vck-taxi-vol-train
            operator: Exists
  volumes:
    - name: dataset-claim
      hostPath:
        path: VCK_HOSTPATH
  containers:
  - image: busybox
    command: ["/bin/sh", "-c"]
    args: ["ls -lisah /data/data.csv && head /data/data.csv && sleep 200 && exit 0"]
    name: vck-taxi
    volumeMounts:
    - mountPath: /data
      name: dataset-claim